### ISSUE TITLE
Groups doesn't work

### ISSUE THREAD

**Issue by fzembow** [cawfree/react-cola#1]
The default `onHandleLayout` does not do anything with the `groups` prop.

Indeed, running the example does not actually render groups as the prop is unused... not sure how you rendered your gif :)

**Comment by cawfree** [comment]
Hey @fzembow! Thanks for trying this library out.

So, let me have a look...

Yep! That's missing. We used props to define the render contents directly, which explains why this functionality is now missing.

I've got my head in a problem currently, so I won't be able to get around to this until later. I'd be super happy to accept a [Pull Request](https://github.com/cawfree/react-cola/pulls) if you're up for it. We can implement a minor version bump if you add append `groups` to the end of the `onHandleLayout` parameter list.

**Comment by fzembow** [comment]
Happy to do it- I’ll integrate into my app and address or document any
other problems I encounter! Probably tomorrow

**Comment by fzembow** [comment]
@cawfree see https://github.com/cawfree/react-cola/pull/2

I'll be using this a bunch more in the next few days so will follow up with more fixes as I find problems

**Comment by cawfree** [comment]
Okay, `0.0.5` is published, so you can now download that back to your project. Again, I'm really sorry for the inconvenience and I really appreciate your help. Best of luck with your work!

**Comment by fzembow** [comment]
@cawfree awesome, thanks!

It's funny, been meaning to add some cola layouts to our react app for a while now, glad you started this package! Enjoy the holidays
