### ISSUE TITLE
0.0.5 npm tarball does not include `dist` directory

### ISSUE THREAD

**Issue by fzembow** [cawfree/react-cola#3]
hi @cawfree I think you forgot to npm run build before publishing 0.0.5

there's no `dist/` folder in there

```
npm view react-cola@0.0.4 dist.unpackedSize
16862

npm view react-cola@0.0.5 dist.unpackedSize
8402
```

you might want to make the publish a package.json script so you don't forget

**Comment by cawfree** [comment]
Hey @fzembow, thanks for spotting! I didn't have the directory `npm install`'d, so the `husky` script was not executed. I've repackaged this now as `0.0.6`. (Thanks for your patience!)

**Comment by fzembow** [comment]
Nice turnaround :)

You might want to specify `files` in package.json and just including `dist/index.js` because then the npm package only contains the output files

https://blog.npmjs.org/post/165769683050/publishing-what-you-mean-to-publish
